annotations:
  artifacthub.io/images: |
    - image: registry.devopsnonprd.vayuktbcs:8082/jupyterhub/configurable-http-proxy:4.5.0
      name: configurable-http-proxy
    - image: registry.devopsnonprd.vayuktbcs:8082/jupyterhub/k8s-hub:1.1.4
      name: k8s-hub
    - image: registry.devopsnonprd.vayuktbcs:8082/jupyterhub/k8s-image-awaiter:1.1.4
      name: k8s-image-awaiter
    - image: registry.devopsnonprd.vayuktbcs:8082/jupyterhub/k8s-network-tools:1.1.4
      name: k8s-network-tools
    - image: registry.devopsnonprd.vayuktbcs:8082/jupyterhub/k8s-secret-sync:1.1.4
      name: k8s-secret-sync
    - image: registry.devopsnonprd.vayuktbcs:8082/chinnapatke01/elyra:vaex-1.3.1
      name: k8s-singleuser-sample
    - image: registry.devopsnonprd.vayuktbcs:8082/nattawut07x/kube-scheduler:v1.19.13
      name: kube-scheduler
    - image: registry.devopsnonprd.vayuktbcs:8082/nattawut07x/pause:3.5
      name: pause
    - image: registry.devopsnonprd.vayuktbcs:8082/nattawut07x/pause:3.5
      name: pause
    - image: registry.devopsnonprd.vayuktbcs:8082/traefik:v2.4.11
      name: traefik
apiVersion: v2
appVersion: 1.4.2
description: Multi-user Jupyter installation
home: https://z2jh.jupyter.org
icon: https://jupyter.org/assets/hublogo.svg
keywords:
- jupyter
- jupyterhub
- z2jh
kubeVersion: '>=1.17.0-0'
maintainers:
- email: erik@sundellopensource.se
  name: Erik Sundell
- name: Simon Li
  url: https://github.com/manics/
name: jupyterhub
sources:
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s
version: 1.1.4
